### PR TITLE
Improved handling of lists, nested lists, strings, and atoms

### PR DESCRIPTION
**Pull request by tobiasgrubenmann**
I created additional support for strings and nested lists in pyswip foreign predicates.

- pyswip foreign predicates now distinguishes between strings and atoms when unifying.
- pyswip foreign predicates can now unify lists of lists (recursive).
- Lists are now unified in a way such that the list can be correctly accessed using the getter method of pyswip.Variable
- It is now possible to register a foreign predicate in a specific module.

I also added tests under test_foreign.py. The tests run successfully with SWI Prolog 8.2.1 and Python 2.7.16 (31bit)

### CODE REVIEW

**Comment by yuce** [comment]
Hi @tobiasgrubenmann, thanks for your contribution. Could you add your name to `CONTRIBUTORS.txt` ?

**Comment by xpinguin** [comment]
Hi! Test doesn't seem to work on Python 3.7 and 3.8 (x86_64):
```
$ python3.7 -m unittest -v tests.test_foreign
test_atoms_and_strings_distinction (tests.test_foreign.MyTestCase) ... ERROR
test_deterministic_foreign (tests.test_foreign.MyTestCase) ... ERROR
test_nested_lists (tests.test_foreign.MyTestCase) ... ERROR
test_nondeterministic_foreign (tests.test_foreign.MyTestCase) ... ERROR
test_register_with_module (tests.test_foreign.MyTestCase) ... ERROR
test_unifying_list_correctly (tests.test_foreign.MyTestCase) ... /home/vns/src2/pyswip/tests/test_foreign.py:71: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(variable.value, [1, 2], 'Lists should be unifyed correctly.')
ok

======================================================================
ERROR: test_atoms_and_strings_distinction (tests.test_foreign.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vns/src2/pyswip/tests/test_foreign.py", line 65, in test_atoms_and_strings_distinction
    result = list(prolog.query("get_str(String), test_for_string(String, Result)"))
  File "/home/vns/src2/pyswip/pyswip/prolog.py", line 129, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'get_str(String), test_for_string(String, Result)'. Returned: 'error(existence_error(procedure, /(get_str, 1)), context(:(system, /(<meta-call>, 1)), Variable(76)))'.

======================================================================
ERROR: test_deterministic_foreign (tests.test_foreign.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vns/src2/pyswip/tests/test_foreign.py", line 18, in test_deterministic_foreign
    result = list(prolog.query("father(michael,X), hello(X)"))
  File "/home/vns/src2/pyswip/pyswip/prolog.py", line 129, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'father(michael,X), hello(X)'. Returned: 'error(existence_error(procedure, /(hello, 1)), context(:(system, /(<meta-call>, 1)), Variable(76)))'.

======================================================================
ERROR: test_nested_lists (tests.test_foreign.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vns/src2/pyswip/tests/test_foreign.py", line 83, in test_nested_lists
    result = list(prolog.query("get_list_of_lists(Result)"))
  File "/home/vns/src2/pyswip/pyswip/prolog.py", line 129, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'get_list_of_lists(Result)'. Returned: 'error(existence_error(procedure, /(get_list_of_lists, 1)), context(/(pyrun, 2), Variable(76)))'.

======================================================================
ERROR: test_nondeterministic_foreign (tests.test_foreign.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vns/src2/pyswip/tests/test_foreign.py", line 44, in test_nondeterministic_foreign
    result = list(prolog.query("nondet(X)"))
  File "/home/vns/src2/pyswip/pyswip/prolog.py", line 129, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'nondet(X)'. Returned: 'error(existence_error(procedure, /(nondet, 1)), context(/(pyrun, 2), Variable(76)))'.

======================================================================
ERROR: test_register_with_module (tests.test_foreign.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vns/src2/pyswip/tests/test_foreign.py", line 96, in test_register_with_module
    result = list(prolog.query("my_module:get_int(Result)"))
  File "/home/vns/src2/pyswip/pyswip/prolog.py", line 129, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'my_module:get_int(Result)'. Returned: 'error(existence_error(procedure, :(my_module, /(get_int, 1))), context(/(pyrun, 2), Variable(78)))'.

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (errors=5)
```

Everything is OK with Python 2.7 (x86_64):
```
$ python2 -m unittest -v tests.test_foreign
test_atoms_and_strings_distinction (tests.test_foreign.MyTestCase) ... ok
test_deterministic_foreign (tests.test_foreign.MyTestCase) ... ('Hello,', Atom('492677'))
('Hello,', Atom('492933'))
ok
test_nested_lists (tests.test_foreign.MyTestCase) ... ok
test_nondeterministic_foreign (tests.test_foreign.MyTestCase) ... ok
test_register_with_module (tests.test_foreign.MyTestCase) ... ok
test_unifying_list_correctly (tests.test_foreign.MyTestCase) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.002s

OK
```

SWI-Prolog version:
```
$ swipl --version
SWI-Prolog version 8.2.1 for x86_64-linux
```
---

I'll try to look in it tomorrow (as functionality provided is extremely useful for me, thanks @tobiasgrubenmann !), get to go afk now... Nevertheless, posted it here in case you'd perhaps have a time to attend the problem prior to me.

**Comment by tobiasgrubenmann** [comment]
Hi all,

Sorry that it took so long. Unfortunately, I didn't receive notifications of this discussion, even though I'm subscribed. Need to look into this.

@xpinguin Thanks for the feedback. I had a look into it and fixed it. There were two problems with Python 3.8. First, I needed to cast the string in the test because in Python 3.8 it was converted to a bytes string. Second, I needed to remove the module support because for some reason PL_register_foreign_in_module is not working in Python 3.8. That's why you get all these "existence_error" messages.

@yuce I added myself to the contributors

I tested the code with Python 2.7 and Python 3.8 using SWI Prolog 8.2.4 (32 bit).

Unfortunately, after merging with the newest version of pyswip, I got some errors regarding access violations in Windows. However, I think that this is unrelated to this pull request. Would be good if someone using another OS could confirm that my pull request still works with the newest version of pyswip. I will further investigate this problem and create an issue, once I know what's going on. (It could also be a problem of my setup.)

**Comment by tobiasgrubenmann** [comment]
Update: I managed to fix the issue when merging with the newest version of master. It turns out that the order of the imports in the __init__.py needs to be changed. Otherwise, there is an access violation on Windows. I wonder if this is just a Windows related issue.

Also, I noticed that the order of the imports was changed recently in one of the commits. Has this been done in order to accommodate some issues? I hope that there are no mutually exclusive requirements for the ordering of these imports for different environments. That would be unfortunate.

**Comment by yuce** [comment]
@tobiasgrubenmann Thanks for your contribution!

**Pull request merged**
