### PR TITLE
Adding PL_STRINGS_MARK to getAtomChars 

### LINKED ISSUE #102: FATAL ERROR: Too many stacked strings
I have a large database (817718 facts) in the form of:
```
actor(actor_519105,m).
actor(actor_524655,m).
actor(actor_475182,m).
actor(actor_370794,m).
actor(actor_389977,m).
actor(actor_213427,m).
actor(actor_380131,m).
actor(actor_302008,m).
actor(actor_171966,m).
actor(actor_291,m).
...
```

When I try to run:
```python
from pyswip import Prolog

prolog = Prolog()
prolog.consult('test.pl')
for r in prolog.query('actor(A,_)'):
    print(r)
```
then is crashes with:
```
{'A': 'actor_44508'}
{'A': 'actor_60096'}
{'A': 'actor_66141'}
{'A': 'actor_95401'}
....
[FATAL ERROR: at Thu Aug 27 17:32:11 2020
        Too many stacked strings]
```

Also, if instead of `print(r)` I just put `pass`, it crashes as well.

If I do the same in Prolog then is succeeds without any issues:
```
['test.pl'].
set_prolog_flag(answer_write_options,[max_depth(0)]).
findall(A, actor(A,_), L).
```
If I use `findall` in Python, like:
```python
L = list(prolog.query('findall(A, actor(A,_), L)'))[0]['L']
for r in L:
    print(r.value)
```
then it crashes as well.

With a smaller database this doesn't happen.
Any ideas?

### PR DESCRIPTION
**Pull request by vakker**
This resolves #102 based on the discussion [here](https://github.com/SWI-Prolog/swipl-devel/issues/660).
I'm not sure if this `PL_STRINGS_MARK` should be used elsewhere, but adding it to `getAtomChars` resolves the issue that I was facing.

### CODE REVIEW

**Comment by vakker** [comment]
Actually, with a big enough database it still crashes (but later), so there might be something else that requires the context manager.
After moving `PL_STRINGS_MARK` to `getTerm` it does work with my database that has 5550248 facts.
I'm not sure if this is the right solution, so let me know if there's anything else that need to be changed.

**Comment by yuce** [comment]
@vakker Thanks for your contribution! Could you add your name to `CONTRIBUTORS.txt` ?

**Comment by vakker** [comment]
@yuce Thanks for pointing it out.
If there's anything else, please let me know.

**Comment by yuce** [comment]
It would be great to have a test case for the fix if it's not too time consuming for you. Creating a Prolog file with 900k facts on-the-fly then consulting & iterating on that file would trigger the crash (without your fix), wouldn't it?

**Comment by yuce** [comment]
If so, I guess that would make a good test case.

**Comment by vakker** [comment]
Yeah, I was thinking about that as well. It takes some time to run it (1-2 min), but it's not hard to add it.

**Comment by vakker** [comment]
@yuce done.
It takes 88s instead of 4s on my machine.
The new test passes with the fix and crashes without it.
Let me know if there's anything else to add.

**Comment by yuce** [comment]
@vakker Thanks a lot!

**Pull request merged**
